cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
import:
  - '@kurone-kito/cspell-config'
version: '0.2'
words:
  - bazi
  - coef
  - dantalion
  - dcoef
  - dedup
  - desync
  - desynced
  - desctiptions
  - esync
  - febrary
  - ganzhi
  - generical
  - gsub
  - goetia
  - isort
  - koshi
  - lemegeton
  - nektos
  - ommited
  - pylint
  - pyproject
  - pytest
  - saintist
  - unpushed
  - unreplied
  - undispositioned
  - unmigrated
  - unreviewable
  - unscored
  - unwaived
  - toctou
  - waivable
  - ziweidoushu
