allowCompoundWords: true
cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
import:
  - '@kurone-kito/cspell-config'
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .github/CONTRIBUTING.*
  - .vscode/extensions.json
  - pnpm-lock.yaml
version: '0.2'
useGitignore: true
words:
  - bazi
  - CODEOWNER
  - CODEOWNERS
  - coef
  - dantalion
  - dedup
  - desync
  - desynced
  - dcoef
  - desctiptions
  - esync
  - ganzhi
  - generical
  - GHEC
  - GHES
  - gsub
  - goetia
  - idd
  - includ
  - isort
  - koshi
  - Kiro
  - lemegeton
  - nektos
  - ONNX
  - pylint
  - pyproject
  - pytest
  - saintist
  - TOCTOU
  - toctou
  - undispositioned
  - unioned
  - unmigrated
  - unmirrored
  - unpushed
  - unreplied
  - unrouted
  - unscored
  - unwaived
  - unreviewable
  - waivable
  - minimizable
  - nvmrc
  - remediations
  - resumability
  - rollup
  - vrchat
  - ziweidoushu
