name: CI/CD on master branch
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - '16.x'
        cache-key:
          - '19a27acd-b393-4a8a-a09f-276a4663454d'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: set npm config
        run: npm config set unsafe-perm true
      - name: Determine npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Persist the cache of dependent packages.
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ matrix.cache-key }}_${{ runner.os }}-node_v${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.cache-key }}_${{ runner.os }}-node_v${{ matrix.node-version }}-
            ${{ matrix.cache-key }}_${{ runner.os }}-node_v
            ${{ matrix.cache-key }}_${{ runner.os }}-node-
            ${{ matrix.cache-key }}_${{ runner.os }}-
      - run: npm ci --legacy-peer-deps
      - run: npm run prepack
        env:
          CI: true
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
      - name: Deploy the build result.
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/dantalion-web-playground/dist
